version: "3.7"

services:
  app:
    image: node
    command: sh -c "yarn install && yarn run dev"
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    env_file:
      - variables.env
