version: "3.7"

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080

  tests:
    build: 
      context: ./src/test/
      dockerfile: Dockerfile
    environment:
      SERVICE_NAME: api
      API_PORT: "3000" 